In [3]:
import numpy as np
# create the range using:  arange()
arr_range=np.arange(2,15,2)
print(arr_range)

[ 2  4  6  8 10 12 14]


In [7]:
# Create linspace 
line_space=np.linspace(0,1,5)
print(line_space)

[0.   0.25 0.5  0.75 1.  ]


In [8]:
# CREATE the random array
array=np.random.rand(3,4)
array

array([[0.54819861, 0.86187635, 0.04913345, 0.5704957 ],
       [0.62422111, 0.94236051, 0.48342973, 0.84724522],
       [0.96659761, 0.84293513, 0.07346984, 0.26966551]])

In [12]:
# generate integer random array
array=np.random.randint(1,4,(4,4))
print(array)

[[3 3 3 1]
 [1 1 2 3]
 [1 1 1 2]
 [2 3 1 2]]


In [13]:
age=np.random.randint(20,30,100)
age

array([29, 27, 22, 23, 22, 28, 24, 26, 20, 28, 24, 29, 23, 21, 26, 23, 26,
       29, 20, 24, 26, 27, 21, 21, 21, 24, 25, 22, 26, 24, 23, 27, 21, 28,
       20, 25, 24, 25, 24, 27, 24, 22, 25, 21, 20, 20, 27, 22, 24, 24, 27,
       26, 26, 25, 20, 22, 29, 25, 21, 24, 28, 22, 29, 27, 26, 25, 21, 22,
       21, 25, 23, 27, 24, 23, 24, 27, 27, 23, 26, 23, 23, 26, 29, 20, 25,
       23, 21, 26, 28, 29, 27, 21, 25, 27, 27, 29, 28, 27, 22, 28],
      dtype=int32)

In [15]:
list1=[1,2,4,9,8]
array=np.array(list1)
array

array([1, 2, 4, 9, 8])

In [17]:
arr=np.array([[3,6,3],[4,6,9]])
arr

array([[3, 6, 3],
       [4, 6, 9]])

In [21]:
# method 1 shape
arr.shape

(2, 3)

In [22]:
# method 2 size
arr.size

6

In [23]:
# method 3 ndim
arr.ndim

2

In [25]:
# method 4 dtype  of array
arr.dtype

dtype('int64')

In [26]:
# check the memory of array
arr.nbytes

48

In [28]:
# traspose array
arr.T

array([[3, 4],
       [6, 6],
       [3, 9]])

In [33]:
# create the complex number
a=np.array([1+2j,3+4j])
a.real
a.imag
a


array([1.+2.j, 3.+4.j])

In [34]:
# flat = multi dimension array convert into single dimension array


In [35]:
# axis=1 in sum

In [39]:
# reshape
a=np.array([1,4,5,6,4,3])
a.reshape(3,2)

array([[1, 4],
       [5, 6],
       [4, 3]])

In [41]:
# sort
# variance 
list1=["Male","female"]
np.random.choice(list1,100)

# uniform 
# np.random.uniform(1000,25000,100)


array(['female', 'female', 'Male', 'female', 'Male', 'female', 'Male',
       'female', 'Male', 'female', 'female', 'Male', 'Male', 'female',
       'Male', 'female', 'Male', 'Male', 'Male', 'Male', 'female',
       'female', 'Male', 'female', 'Male', 'Male', 'female', 'Male',
       'Male', 'female', 'Male', 'Male', 'Male', 'female', 'Male',
       'female', 'Male', 'Male', 'female', 'female', 'Male', 'female',
       'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male',
       'female', 'Male', 'Male', 'female', 'Male', 'Male', 'Male', 'Male',
       'female', 'female', 'female', 'Male', 'Male', 'female', 'female',
       'Male', 'female', 'Male', 'female', 'Male', 'female', 'Male',
       'female', 'female', 'female', 'female', 'female', 'Male', 'Male',
       'Male', 'female', 'female', 'Male', 'female', 'female', 'Male',
       'female', 'Male', 'Male', 'female', 'Male', 'female', 'Male',
       'Male', 'Male', 'female', 'female', 'female', 'Male', 'Male'],
      dtype='

In [42]:
# id:100
# name columns
# gnder column
# dept column
# exp
# role
# salary

In [46]:
import pandas as pd
import numpy as np

np.random.seed(10)
id=np.arange(100,600)
name=np.random.choice(["Ravi","Amit","Rahul","Sameer","Vikas",
     "Priya"], 500)
gender=np.random.choice(["Male","Female"],500)
dept = np.random.choice(
    ["IT","HR","Finance","Sales","Marketing","Operations"],500)
exp = np.random.randint(0,16,500)
role = np.random.choice(
    ["Data Analyst","Data Scientist","Software Engineer",
     "HR Executive"], 500)
salary=np.random.randint(25000,120001,500)
df=pd.DataFrame({
    "id":id,
    "name":name,
    "gender":gender,
    "dept":dept,
    "exp":exp,
    "role":role,
    "salary":salary})
print(df)
print(df.shape)

      id    name  gender        dept  exp               role  salary
0    100    Amit  Female  Operations    2       HR Executive   28964
1    101   Priya  Female       Sales    3  Software Engineer   66029
2    102   Vikas  Female          HR    6  Software Engineer   65934
3    103    Ravi  Female   Marketing   15       Data Analyst   57673
4    104    Amit    Male     Finance   11       HR Executive   26387
..   ...     ...     ...         ...  ...                ...     ...
495  595  Sameer  Female       Sales   15     Data Scientist   45181
496  596   Rahul  Female       Sales    5       Data Analyst   58839
497  597    Ravi    Male  Operations    6       Data Analyst   36072
498  598   Vikas  Female          IT   12       HR Executive   77923
499  599  Sameer    Male   Marketing    1       HR Executive   56728

[500 rows x 7 columns]
(500, 7)
